const icecreams = [
  {
    id: '1',
    name: 'Vanilla',
    price: 2.99,
    description: 'Classic vanilla ice cream',
    likes: 20,
    image: 'vanilla.jpg',
  },
  {
    id: '2',
    name: 'Mint Chocolate Chip',
    price: 4.49,
    description: 'Refreshing mint ice cream with chocolate chips',
    likes: 12,
    image: 'mint-chocolate-chip.jpg',
  },
  {
    id: '3',
    name: 'Cookies and Cream',
    price: 3.99,
    description: 'Creamy ice cream with chocolate cookie pieces',
    likes: 18,
    image: 'cookies-and-cream.jpg',
  },
  {
    id: '4',
    name: 'Strawberry Cheesecake',
    price: 4.99,
    description: 'Creamy strawberry ice cream with cheesecake bits',
    likes: 15,
    image: 'strawberry-cheesecake.jpg',
  },
  {
    id: '5',
    name: 'Rocky Road',
    price: 4.49,
    description: 'Chocolate ice cream with marshmallows and nuts',
    likes: 10,
    image: 'rocky-road.jpg',
  },
  {
    id: '6',
    name: 'Pistachio',
    price: 3.99,
    description: 'Rich pistachio-flavored ice cream',
    likes: 8,
    image: 'pistachio.jpg',
  },
  {
    id: '7',
    name: 'Caramel Swirl',
    price: 4.49,
    description: 'Creamy ice cream with swirls of caramel',
    likes: 14,
    image: 'caramel-swirl.jpg',
  },
  {
    id: '8',
    name: 'Banana Split',
    price: 5.49,
    description: 'A classic banana split with multiple flavors',
    likes: 22,
    image: 'banana-split.jpg',
  },
  {
    id: '9',
    name: 'Coffee',
    price: 3.99,
    description: 'Smooth coffee-flavored ice cream',
    likes: 9,
    image: 'coffee.jpg',
  },
  {
    id: '10',
    name: 'Rainbow Sherbet',
    price: 3.49,
    description: 'Refreshing and fruity rainbow sherbet',
    likes: 17,
    image: 'rainbow-sherbet.jpg',
  },
];

export default icecreams
